[profile.default]
solc-version = '0.8.26'
src = 'contracts'
out = 'out'
test = 'test/foundry'
fs_permissions = [{ access = "read", path = "./data"}]
cache_path = 'cache/foundry'
ffi = true
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[rpc_endpoints]
local = "http://localhost:8545"
eth = "https://mainnet.gateway.tenderly.co"
base = "https://base.gateway.tenderly.co"
arb = "https://arbitrum.gateway.tenderly.co"
avax = "https://avalanche-mainnet.gateway.tenderly.co"
op = "https://optimism.gateway.tenderly.co"
polygon = "https://polygon.gateway.tenderly.co"
peaq = "https://peaq.api.onfinality.io/public"
sepolia = "https://sepolia.gateway.tenderly.co"
arb-sep = "https://arbitrum-sepolia.gateway.tenderly.co"
op-sep = "https://optimism-sepolia.gateway.tenderly.co"
base-sep = "https://base-sepolia.gateway.tenderly.co"
amoy = "https://polygon-amoy.gateway.tenderly.co"
holesky = "https://holesky.gateway.tenderly.co"
bob = "https://bob.gateway.tenderly.co"
blast = "https://blast.gateway.tenderly.co"
taiko = "https://taiko-mainnet.gateway.tenderly.co"
fraxtal = "https://fraxtal.gateway.tenderly.co"
metis-andromeda = "https://metis-andromeda.gateway.tenderly.co"
imx = "https://immutable.gateway.tenderly.co"
lisk = "https://lisk.gateway.tenderly.co"
boba-eth = "https://boba-ethereum.gateway.tenderly.co"
arb-nova = "https://arbitrum-nova.gateway.tenderly.co"
boba-bnb = "https://boba-bnb.gateway.tenderly.co"
worldchain = "https://worldchain-mainnet.gateway.tenderly.co"
worldchain-sep = "https://worldchain-sepolia.gateway.tenderly.co"
boba-bnb-testnet = "https://boba-bnb-testnet.gateway.tenderly.co"
boba-sep = "https://boba-sepolia.gateway.tenderly.co"
mode = "https://mode.gateway.tenderly.co"
metis-sep = "https://metis-sepolia.gateway.tenderly.co"
mumbai = "https://polygon-mumbai.gateway.tenderly.co"
tangible-real = "https://tangible-real.gateway.tenderly.co"
taiko-hekla = "https://taiko-hekla.gateway.tenderly.co"